id: P009581
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN6685
  title: བུ་ལྡོམ་པོ་དང་ཀླུའི་སྲས་མོ།
  author: ''
  volumes:
    5e5576ce0f314582988cea5eb956b4c5:
      image_group_id: I3CN6687
      title: ''
      volume_number: 1
      total_pages: 86
