id: IDA73F476
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T12:06:01+00:00'
last_modified: '2022-06-08T12:02:40.978942+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN6685
  title: བུ་ལྡོམ་པོ་དང་ཀླུའི་སྲས་མོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    9CC4:
      image_group_id: I3CN6687
      title: ''
      total_pages: 86
      order: 1
      base_file: 9CC4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
